# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# THREADS_PTHREAD_ARG
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set THREADS_PTHREAD_ARG to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The THREADS_HAVE_PTHREAD_ARG variable holds the build result for this TRY_RUN().
# 
# Source file   : /usr/local/Cellar/cmake/3.1.1_1/share/cmake/Modules/CheckForPthreads.c
# Executable    : /Users/Shea/Projects/dangerengine/jsbuild/CMakeFiles/cmTryCompileExec1310549161-THREADS_PTHREAD_ARG.js
# Run arguments : 
#    Called from: [2]	/usr/local/Cellar/cmake/3.1.1_1/share/cmake/Modules/FindThreads.cmake
#                 [1]	/Users/Shea/Projects/dangerengine/extern/kazmath/kazmath/CMakeLists.txt

set( THREADS_PTHREAD_ARG 
     "PLEASE_FILL_OUT-FAILED_TO_RUN"
     CACHE STRING "Result from TRY_RUN" FORCE)

